<?php

namespace App\Mark\Actions;

use Dcat\Admin\Actions\Action;
use Dcat\Admin\Actions\Response;
use Dcat\Admin\Grid\RowAction;
use Dcat\Admin\Traits\HasPermissions;
use Dcat\Admin\Widgets\Modal;
use Illuminate\Contracts\Auth\Authenticatable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;
use SimpleSoftwareIO\QrCode\Facades\QrCode;

class AccountCodeAction extends RowAction
{
    /**
     * @return string
     */
	protected $title = '扫码配置';

    /**
     * Handle the action request.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function handle(Request $request)
    {
        // dump($this->getKey());

        return $this->response()->success('Processed successfully.')->redirect('/');
    }

    /**
     * @return string|array|void
     */
    public function confirm()
    {
        // return ['Confirm?', 'contents'];
    }

    /**
     * @param Model|Authenticatable|HasPermissions|null $user
     *
     * @return bool
     */
    protected function authorize($user): bool
    {
        return true;
    }

    /**
     * @return array
     */
    protected function parameters()
    {
        return [];
    }

    public function render()
    {
        // dd('alipays://platformapi/startapp?appId=2021003130652097&page='.urlencode('pages/authorize/index?bizData={"platformCode":"O","taskType":"INTERFACE_AUTH","agentOpParam":{"redirectUri":"https://kkk.luozhansicun.cn/aliAuth","appTypes":["TINYAPP","WEBAPP","PUBLICAPP"],"isvAppId":"2021004113683064"}}'));
        // dump('https://openauth.alipay.com/oauth2/appToAppAuth.htm?app_id=2021004113683064&redirect_uri=https%3A%2F%2Fkkk.luozhansicun.cn%2FaliAuth?account='.$this->getKey());
//        return parent::render(); // TODO: Change the autogenerated stub
        $body = QrCode::size('150')->generate('alipays://platformapi/startapp?appId=2021003130652097&page='.urlencode('pages/authorize/index?bizData={"platformCode":"O","taskType":"INTERFACE_AUTH","agentOpParam":{"redirectUri":"https://kkk.luozhansicun.cn/aliAuth?account='.$this->getKey().'","appTypes":["TINYAPP","WEBAPP","PUBLICAPP"],"isvAppId":"2021004113683064"}}'));;
        return Modal::make()->sm()->centered()->title($this->title)->body($body)->button('<i class="fa fa-eye">配置信息</i> ');
    }
}
