<?php

namespace App\Models;

use Dcat\Admin\Admin;
use Dcat\Admin\Traits\HasDateTimeFormatter;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class ChannelAccount extends Model
{
	use HasDateTimeFormatter;
	use SoftDeletes;
    protected $table = 'channel_account';

    protected $guarded = ['id'];

    protected $dateFormat = 'U';

    public function getCreatedAtAttribute($timestamp)
    {
        $date = new \DateTime();
        $timestamp = $date->setTimestamp($timestamp);
        return $timestamp->format('Y-m-d H:i');
    }

    public function getUpdatedAtAttribute($timestamp)
    {
        $date = new \DateTime();
        $timestamp = $date->setTimestamp($timestamp);
        return $timestamp->format('Y-m-d H:i');
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        $admin = Admin::user();
        if($admin){
            if($admin->table == 'admin_users'){
                if($admin['id'] != 1 || $admin['id'] != 4){
                    
                }else{
                    $arr = User::where("admin", $admin['id'])->pluck('id')->toArray();
                    static::addGlobalScope('avaiable', function(Builder $builder) use ($arr){
                                $builder->whereIn('uid', $arr);
                            });
                }
            
        }else{
            if($admin){
                $user = $admin['id'];
                $type = $admin['type'];
                if($type == 'code'){
                    static::addGlobalScope('avaiable', function(Builder $builder) use ($user){
                        $builder->where('uid', $user);
                    });
                }
            }
        }

        }
        
    }
}
