<?php

namespace App\Models;

use Dcat\Admin\Admin;
use Dcat\Admin\Traits\HasDateTimeFormatter;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;

class ComplaintList extends Model
{
	use HasDateTimeFormatter;
    protected $table = 'complaint_list';
    public $timestamps = false;

    protected $guarded = ['id'];

    protected static function boot()
    {
        $ids = request()->input('id');
        parent::boot(); // TODO: Change the autogenerated stub
        if(!empty($ids)){
            static::addGlobalScope('avaiable', function(Builder $builder) use ($ids){
                $builder->where('pid', $ids);
            });
        }
    }


}
