<?php

namespace App\Models;

use Dcat\Admin\Admin;
use Dcat\Admin\Traits\HasDateTimeFormatter;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class UserChannel extends Model
{
	use HasDateTimeFormatter;
    use SoftDeletes;

    protected $dates = ['deleted_at'];

    protected $table = 'user_channel';

    protected $dateFormat = 'U';

    public $timestamps = false;


    public function channel()
    {
        return $this->hasOne(Channel::class, 'id', 'cid');
    }


    protected static function boot()
    {
        parent::boot();    //TODO: Change the autogenerated stub
        $admin = Admin::user();
        if($admin){
            if($admin->table == 'admin_users'){
                if($admin['id'] != 1){
                    if($admin['id'] != '4'){
                        $userId = User::where('admin', $admin['id'])->pluck('id')->toArray();
                        static::addGlobalScope('avaiable', function(Builder $builder) use ($userId){
                            $builder->whereIn('uid', $userId);
                        });
                    }
                    
                }
        }
        }
        

    }

}
